version: "3"
services:
  directus:
    image: directus/directus:11.0.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "YhoZFP9fB8Umpdk35zrD8XCLqlz5nPT6"
      ADMIN_EMAIL: "admin@gmail.com"
      ADMIN_PASSWORD: "eiwhsabwhs"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      CORS_ENABLED: true
      CORS_ORIGIN: "http://localhost:3000"
  client-app:
    image: node:20
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    command: bash -c "cd /app && npm install && npm run dev"
